/* Use SQLPlus */

CREATE TABLE  CANDIDATE 
(
CANDIDATE_ID varchar2(10), 
NAME varchar2(20), 
PARTY varchar2(10),
CONSTRAINT pk_CANDIDATE_ID PRIMARY KEY (CANDIDATE_ID)
);

CREATE TABLE PROPOSITION 
(
PROPOSITION_ID varchar2(10), 
DESCRIPTION varchar2(100),
CONSTRAINT pk_PROPOSITION_ID PRIMARY KEY (PROPOSITION_ID)
);

CREATE SEQUENCE counter
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

CREATE TABLE VOTER
(
VOTER_ID NUMBER, 
FIRST_NAME varchar2(25), 
LAST_NAME varchar2(25), 
BIRTH_DATE DATE, 
FAMILY_STATUS varchar2(15), 
PARTY_AFFILIATION varchar2(20), 
PHONE_NUMBER Number(10), 
HOME_ADDRESS varchar2(50) , 
CONSTRAINT pk_VOTER_ID PRIMARY KEY (VOTER_ID)
);

CREATE TABLE DONOR 
(
VOTER_ID NUMBER, 
DONOR_TIN Number(10), 
POTENTIAL_LARGE_DONOR_FLAG varchar2(1), 
CONSTRAINT fk_DONOR_VOTER_ID FOREIGN KEY (VOTER_ID) REFERENCES VOTER(VOTER_ID),
CONSTRAINT pk_DONOR PRIMARY KEY (DONOR_TIN)
);

CREATE TABLE DONATION 
(
VOTER_ID NUMBER, 
DONATION_DATE DATE, 
AMOUNT Number(5,2),
CONSTRAINT pk_DONATION_ID PRIMARY KEY (VOTER_ID, DONATION_DATE),
CONSTRAINT fk_DONATION_VOTER_ID FOREIGN KEY (VOTER_ID) REFERENCES VOTER(VOTER_ID)
);

CREATE TABLE CATEGORY 
(
CATEGORY_ID varchar2(10), 
DESCRIPTION varchar2(30),
CONSTRAINT pk_CATEGORY_ID PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE CANDIDATE_PROPOSITION 
(
CANDIDATE_ID varchar2(10), 
PROPOSITION_ID varchar2(10), 
CONSTRAINT fk_CP_CANDIDATE_ID FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID),
CONSTRAINT fk_CP_PROPOSITION_ID FOREIGN KEY (PROPOSITION_ID) REFERENCES PROPOSITION(PROPOSITION_ID),
CONSTRAINT pk_CANDIDATE_PROPOSITION PRIMARY KEY (CANDIDATE_ID, PROPOSITION_ID)
);

CREATE TABLE VOTER_PROPOSITION 
(
VOTER_ID NUMBER, 
PROPOSITION_ID varchar2(10),
CONSTRAINT fk_VP_VOTER_ID FOREIGN KEY (VOTER_ID) REFERENCES VOTER(VOTER_ID),
CONSTRAINT fk_VP_PROPOSITION_ID FOREIGN KEY (PROPOSITION_ID) REFERENCES PROPOSITION(PROPOSITION_ID),
CONSTRAINT pk_VOTER_PROPOSITION PRIMARY KEY (VOTER_ID, PROPOSITION_ID)
);

CREATE TABLE VOTER_CATEGORY 
(
VOTER_ID NUMBER, 
CATEGORY_ID varchar2(10),
CONSTRAINT fk_VC_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
CONSTRAINT fk_VC_VOTER_ID FOREIGN KEY (VOTER_ID) REFERENCES VOTER(VOTER_ID),
CONSTRAINT pk_VOTER_CATEGORY PRIMARY KEY (VOTER_ID, CATEGORY_ID)
);

CREATE TABLE DONOR_RELATIONSHIP 
(
DONOR_ID NUMBER(10), 
RELATED_VOTER_ID NUMBER,
CONSTRAINT fk_DR_VOTER_ID FOREIGN KEY (RELATED_VOTER_ID) REFERENCES VOTER(VOTER_ID),
CONSTRAINT fk_DR_DONOR_ID FOREIGN KEY (DONOR_ID) REFERENCES DONOR(DONOR_TIN),
CONSTRAINT pk_DONOR_RELATIONSHIP PRIMARY KEY (DONOR_ID, RELATED_VOTER_ID)
);

CREATE TABLE STAFF_ITINERARY 
(
LOCATION varchar2(15), 
CONTACT_PHONE Number(10), 
EVENT_DATE DATE, 
EVENT_TIME DATE, 
DURATION Number(2), 
STAFFER_NAME varchar2(25), 
EVENT varchar2(40),
CONSTRAINT pk_STAFF_ITINERARY PRIMARY KEY (LOCATION, EVENT_DATE, EVENT_TIME, STAFFER_NAME) 
);

CREATE TABLE VENDOR_PAYMENT 
(
VENDOR_ID varchar2(10), 
NAME varchar2(25), 
PAYMENT_DATE DATE, 
AMOUNT Number(5),
CONSTRAINT pk_VENDOR_PAYMENT PRIMARY KEY (VENDOR_ID, PAYMENT_DATE)
);


/* Insert Data */

INSERT INTO   CANDIDATE
(CANDIDATE_ID, NAME, PARTY) 
VALUES 
('C1', 'Rabblerouser O.', 'Democrat');

INSERT INTO CANDIDATE
(CANDIDATE_ID, NAME, PARTY) 
VALUES 
('C2', 'Hilarious C.', 'Democrat');

INSERT INTO CANDIDATE
(CANDIDATE_ID, NAME, PARTY) 
VALUES 
('C3', 'Muddled R.', 'Republican');

INSERT INTO CATEGORY 
(CATEGORY_ID, DESCRIPTION) 
VALUES 
('124','MALE/ FEMALE');

INSERT INTO CATEGORY 
(CATEGORY_ID, DESCRIPTION) 
VALUES 
('125','RACE');
 
INSERT INTO CATEGORY 
(CATEGORY_ID, DESCRIPTION) 
VALUES 
('126','POOR/ MIDDLE/ RICH');

INSERT INTO PROPOSITION
(PROPOSITION_ID, DESCRIPTION) 
VALUES 
('P1','Mere possession of any non-sentient thing or substance shall not be a crime in our country');

INSERT INTO PROPOSITION
(PROPOSITION_ID, DESCRIPTION) 
VALUES 
('P2','Any agency that seizes cash without a court order shall be guilty of a felony');

INSERT INTO PROPOSITION
(PROPOSITION_ID, DESCRIPTION) 
VALUES 
('P3','The right to bear arms shall be clarified and enhanced');

INSERT INTO VOTER
(VOTER_ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, FAMILY_STATUS, PARTY_AFFILIATION, PHONE_NUMBER, HOME_ADDRESS)
VALUES 
(COUNTER.NEXTVAL, 'SMITH', 'TAILOR', TO_DATE('1980/04/11', 'yyyy/mm/dd'), 'MARRIED', 'DEMOCRATIC', 1234567890, '123, 100TH ST, SANTA CLARA');

INSERT INTO VOTER
(VOTER_ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, FAMILY_STATUS, PARTY_AFFILIATION, PHONE_NUMBER, HOME_ADDRESS)
VALUES 
(COUNTER.NEXTVAL, 'TOM', 'CRUIZ', TO_DATE('1989/06/20', 'yyyy/mm/dd'), 'MARRIED', 'DEMOCRATIC', 1122112211, '101, FULLER ST, SUNNYVALE');

INSERT INTO VOTER
(VOTER_ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, FAMILY_STATUS, PARTY_AFFILIATION, PHONE_NUMBER, HOME_ADDRESS)
VALUES 
(COUNTER.NEXTVAL, 'LINDA', 'RAY', TO_DATE('1992/06/20', 'yyyy/mm/dd'), 'SINGLE', 'REPUBLICAN', 8980001234, '2ND ST, SAN JOSE');

COMMIT;
